let state={mode:"practice",name:"Line Cook",queue:[],qi:0,step:0,score:0,combo:0,misses:0,specs:0,specsOk:0,perfects:0,ticketsOk:0,started:0,timer:null,left:0,hintT:null,specOpen:false,beginDone:false};
function $(id){return document.getElementById(id);}
function show(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("on"));$(id).classList.add("on");}
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function rankFor(score){let r=RANKS[0][1];for(const [n,name] of RANKS) if(score>=n) r=name;return r;}
function loadBoard(){try{return JSON.parse(localStorage.getItem("clubChampBoard")||"[]");}catch(e){return [];}}
function saveBoard(entry){const b=loadBoard();b.push(entry);b.sort((a,c)=>c.score-a.score);localStorage.setItem("clubChampBoard",JSON.stringify(b.slice(0,12)));}
function refreshBest(){const el=$("bestLine");if(!el)return;const b=loadBoard()[0];el.textContent=b?("House best: "+b.name+" · "+b.score+" · "+b.rank):"No champ on the board yet.";}
function playerName(){const n=(($("playerName")&&$("playerName").value)||"").trim()||"Line Cook";try{localStorage.setItem("clubChampName",n);}catch(e){}return n;}
function closeBegin(){state.beginDone=true;const m=$("beginModal");if(m)m.classList.remove("on");if(state.queue&&state.queue.length) startTicket();}
function startMode(mode){try{localStorage.setItem("clubChampName",playerName());}catch(e){}state.mode=mode;state.name=playerName();if($("playerName"))$("playerName").value=state.name;if(mode==="practice"){renderPick();show("pick");return;}if(mode==="quiz"){startQuiz();return;}if(mode==="book"){openBook();return;}const sizes=["c2","whole"];if(mode==="rush"){state.queue=Array.from({length:5},()=>({sand:MENU[Math.floor(Math.random()*MENU.length)],size:sizes[Math.floor(Math.random()*2)]}));}else{state.queue=shuffle(MENU).map(s=>({sand:s,size:sizes[Math.floor(Math.random()*2)]}));}resetSession();maybeBegin(()=>startTicket());}
function renderPick(){$("pickGrid").innerHTML=MENU.map(s=>`<div class="sand-card"><div class="meta">${s.premium?"Premium Ⓟ · ":""}${s.family==="king"?"King family":s.family==="wrap"?"Wrap":"3-slice club"}</div><h3>${s.name}</h3><div class="size-row"><button type="button" data-practice="${s.id}" data-size="c2">C2</button><button type="button" data-practice="${s.id}" data-size="whole">Whole</button></div></div>`).join("");}
function practice(id,size){const sand=MENU.find(s=>s.id===id);state.queue=[{sand,size}];resetSession();maybeBegin(()=>startTicket());}
function resetSession(){state.qi=0;state.score=0;state.combo=0;state.misses=0;state.specs=0;state.specsOk=0;state.perfects=0;state.ticketsOk=0;updateHud();}
function maybeBegin(cb){if(state.beginDone){cb();return;}const items=[["🧼","Clean & sanitize work area"],["✋","Wash hands"],["🛡️","Put on cut glove"],["🧤","Disposable gloves"]];let done=new Set();const grid=$("beginGrid");if(!grid){cb();return;}grid.innerHTML=items.map((it,i)=>`<button class="begin-item" data-i="${i}"><div style="font-size:26px">${it[0]}</div>${it[1]}</button>`).join("");const go=$("beginGo");if(go)go.disabled=true;grid.onclick=(e)=>{const b=e.target.closest(".begin-item");if(!b)return;b.classList.add("done");done.add(b.dataset.i);if(done.size===4&&go)go.disabled=false;};state._beginCb=cb;if(go)go.onclick=closeBegin;$("beginModal").classList.add("on");}
function startTicket(){clearInterval(state.timer);clearTimeout(state.hintT);const t=state.queue[state.qi];state.step=0;state.ticketMiss=0;state.started=Date.now();state.specOpen=false;show("game");$("ticketWho").textContent=GUESTS[Math.floor(Math.random()*GUESTS.length)]+" · "+state.sizeLabel(t.size);$("ticketName").textContent=t.sand.name+(t.sand.premium?"  Ⓟ":"");const p=t.sand.portions[t.size];$("ticketMods").innerHTML=Object.entries(p).map(([k,v])=>"<b>"+k+"</b> "+v).join(" &nbsp;·&nbsp; ");$("hudLabel").textContent=state.mode==="practice"?"Practice":"Ticket";$("hudVal").textContent=(state.qi+1)+" / "+state.queue.length;$("stack").innerHTML="";$("feedback").textContent="Ticket fired. Build it in spec order.";$("hintLine").textContent=state.mode==="practice"?"Station is live. Hint appears if you stall.":"Rush ticket. Stay on spec.";renderBins();if(state.mode!=="practice"){state.left=t.sand.family==="king"?113:88;$("timerEl").textContent=state.left+"s";state.timer=setInterval(()=>{state.left--;$("timerEl").textContent=state.left+"s";if(state.left<=0){clearInterval(state.timer);finishTicket(false,"Time. Ticket died on the board.");}},1000);}else{$("timerEl").textContent="No clock";armHint();}updateHud();}
state.sizeLabel=size=>size==="c2"?"C2":"WHOLE";
function armHint(){clearTimeout(state.hintT);state.hintT=setTimeout(()=>{const t=state.queue[state.qi];if(!t||state.specOpen)return;const step=t.sand.steps[state.step];if(step)$("hintLine").textContent="Hint: "+step.label;},9000);}
function currentNeed(){return state.queue[state.qi].sand.steps[state.step];}
function renderBins(){const t=state.queue[state.qi];const need=currentNeed();const upcoming=t.sand.steps.slice(state.step,state.step+5);const pool=DISTRACTORS.filter(d=>!upcoming.some(s=>s.label===d.label));let bins=[need,...upcoming.slice(1,2),...shuffle(pool).slice(0,4)];bins=shuffle(bins).slice(0,5);if(!bins.some(b=>b.id===need.id))bins[0]=need;bins=shuffle(bins);$("bins").innerHTML=bins.map(b=>`<button class="bin" data-id="${b.id}"><div class="ico">${b.icon}</div>${b.label}</button>`).join("");}
function tapBin(btn){const t=state.queue[state.qi];const need=currentNeed();if(btn.dataset.id===need.id){btn.classList.add("ok");addLayer(need);state.combo++;const speed=Date.now()-(state.lastTap||state.started);state.lastTap=Date.now();let pts=100+Math.min(40,state.combo*5);if(speed<2500)pts+=20;state.score+=pts;$("feedback").textContent="+"+pts+"  ·  "+need.hint;$("hintLine").textContent=need.hint;state.step++;updateHud();if(state.step>=t.sand.steps.length){finishTicket(true);return;}maybeSpec(()=>{renderBins();if(state.mode==="practice")armHint();});}else{btn.classList.add("no");setTimeout(()=>btn.classList.remove("no"),320);state.combo=0;state.misses++;state.ticketMiss=(state.ticketMiss||0)+1;state.score=Math.max(0,state.score-40);const picked=[...t.sand.steps,...DISTRACTORS].find(s=>s.id===btn.dataset.id);const inRecipe=t.sand.steps.some(s=>s.id===btn.dataset.id||s.label===(picked&&picked.label));$("feedback").textContent=inRecipe?("Right family, wrong step. "+(state.ticketMiss>=2?("Need: "+need.label):"Stay in card order.")):("That's not spec on this ticket. "+(state.ticketMiss>=2?("Need: "+need.label):"Read the chit."));if(state.mode==="practice"&&state.ticketMiss>=2)$("hintLine").textContent="Need: "+need.label+" — "+need.hint;updateHud();}}
function addLayer(step){const skip=["toast","heat","heatwrap","lay","roll","cut","picks","plate"];if(skip.includes(step.id))return;const visual=["wheat","whiteb","wrap","mayo","ham","turkey","chicken","beef","cheddar","swiss","hm","hr","bacon","tomato","onion","mix"];if(!visual.includes(step.cls))return;const el=document.createElement("div");el.className="layer "+step.cls;el.textContent=step.label.replace(" — first stack","").replace(" — second stack","");$("stack").appendChild(el);}
function maybeSpec(cb){const chance=state.mode==="practice"?0.11:0.16;if(Math.random()>chance){cb();return;}const t=state.queue[state.qi];const pool=QUIZ.filter(q=>true);const item=pool[Math.floor(Math.random()*pool.length)];askSpec(item,cb);}
function askSpec(item,cb){state.specOpen=true;state.specs++;const choices=shuffle([item.a,...item.w]);$("specQ").textContent=item.q;$("specFeed").textContent="";$("specChoices").innerHTML=choices.map(c=>`<button class="choice">${c}</button>`).join("");$("specChoices").dataset.lock="";$("specModal").classList.add("on");$("specChoices").onclick=e=>{const b=e.target.closest(".choice");if(!b||$("specChoices").dataset.lock)return;$("specChoices").dataset.lock="1";const ok=b.textContent===item.a;b.classList.add(ok?"good":"bad");if(!ok)[...$("specChoices").children].forEach(ch=>{if(ch.textContent===item.a)ch.classList.add("good");});if(ok){state.specsOk++;state.score+=150;$("specFeed").textContent="Spec. +150";}else{state.score=Math.max(0,state.score-50);$("specFeed").textContent="Miss. Card says: "+item.a;}updateHud();setTimeout(()=>{$("specModal").classList.remove("on");state.specOpen=false;cb();},850);};}
function finishTicket(ok,msg){clearInterval(state.timer);clearTimeout(state.hintT);if(ok){state.ticketsOk++;let bonus=300;if(!state.ticketMiss){bonus+=200;state.perfects++;}if(state.mode!=="practice"&&state.left>25)bonus+=80;state.score+=bonus;$("doneTitle").textContent=state.ticketMiss?"Ticket window.":"Clean ticket!";$("doneBody").textContent=(msg||("Plated. +"+bonus+" finish bonus."))+"  "+state.queue[state.qi].sand.steps.slice(-1)[0].hint;}else{$("doneTitle").textContent="Remake.";$("doneBody").textContent=msg||"That one got away.";}updateHud();$("doneModal").classList.add("on");}
function nextTicket(){$("doneModal").classList.remove("on");state.qi++;if(state.qi>=state.queue.length){endSession();return;}startTicket();}
function endSession(){saveBoard({name:state.name,score:state.score,rank:rankFor(state.score),mode:state.mode,at:Date.now()});$("resultTitle").textContent=rankFor(state.score);$("resultScore").textContent=state.score;$("resultRank").textContent=state.name+" · "+state.mode.toUpperCase();$("resultStats").textContent=`Tickets clean: ${state.ticketsOk}/${state.queue.length}   ·   Perfect builds: ${state.perfects}   ·   Spec ${state.specsOk}/${state.specs}   ·   Misses ${state.misses}`;$("boardList").innerHTML=loadBoard().map(r=>`<li><span>${r.name} · ${r.mode}</span><span>${r.score} · ${r.rank}</span></li>`).join("")||"<li>No scores yet</li>";show("results");}
function again(){startMode(state.mode);}
function goHome(){clearInterval(state.timer);clearTimeout(state.hintT);document.querySelectorAll(".modal").forEach(m=>m.classList.remove("on"));refreshBest();show("home");}
function updateHud(){if($("scoreEl"))$("scoreEl").textContent=state.score;if($("rankEl"))$("rankEl").textContent=rankFor(state.score);}
function openBook(){$("bookList").innerHTML=MENU.map(s=>{const w=s.portions.whole,c=s.portions.c2;return `<div class="book-card"><div class="meta" style="font-weight:800;color:#1c6b4f">${s.premium?"Premium Ⓟ · ":""}${s.family}</div><h3>${s.name}</h3><p style="font-weight:700"><b>Whole:</b> ${Object.values(w).join(" · ")}</p><p style="font-weight:700"><b>C2:</b> ${Object.values(c).join(" · ")}</p><ol class="steps-ol">${s.steps.map(st=>`<li>${st.label} — ${st.hint}</li>`).join("")}</ol></div>`;}).join("");show("book");}
let quizQueue=[],quizI=0,quizOk=0;
function startQuiz(){state.name=playerName();quizQueue=shuffle(QUIZ).slice(0,12);quizI=0;quizOk=0;state.score=0;show("quiz");renderQuiz();}
function renderQuiz(){const item=quizQueue[quizI];$("quizProg").textContent=(quizI+1)+" / "+quizQueue.length;$("quizQ").textContent=item.q;$("quizFeed").textContent="";$("quizChoices").dataset.lock="";$("quizChoices").innerHTML=shuffle([item.a,...item.w]).map(c=>`<button class="choice">${c}</button>`).join("");$("quizChoices").onclick=e=>{const b=e.target.closest(".choice");if(!b||$("quizChoices").dataset.lock)return;$("quizChoices").dataset.lock="1";const ok=b.textContent===item.a;b.classList.add(ok?"good":"bad");if(!ok)[...$("quizChoices").children].forEach(ch=>{if(ch.textContent===item.a)ch.classList.add("good");});if(ok){quizOk++;state.score+=120;$("quizFeed").textContent="Spec.";}else $("quizFeed").textContent="Card says: "+item.a;setTimeout(()=>{quizI++;if(quizI>=quizQueue.length){state.queue=quizQueue;state.ticketsOk=quizOk;state.perfects=0;state.specs=quizQueue.length;state.specsOk=quizOk;state.misses=quizQueue.length-quizOk;state.mode="quiz";endSession();}else renderQuiz();},700);};}
try{const saved=localStorage.getItem("clubChampName");if(saved&&$("playerName"))$("playerName").value=saved;}catch(e){}
if($("bestLine"))refreshBest();
(function armTouches(){let lockUntil=0;function launchMode(mode){if(!mode)return;const now=Date.now();if(now<lockUntil)return;lockUntil=now+600;try{localStorage.setItem("clubChampName",playerName());}catch(e){}if(mode==="book")openBook();else startMode(mode);}function onHomeTap(e){const btn=e.target&&e.target.closest&&e.target.closest(".mode-btn");if(!btn)return;if(e.type==="touchend"||e.type==="pointerup")e.preventDefault();launchMode(btn.dataset.mode);}const home=$("home");if(home){home.addEventListener("click",onHomeTap);home.addEventListener("pointerup",e=>{if(e.pointerType!=="mouse")onHomeTap(e);},{passive:false});home.addEventListener("touchend",onHomeTap,{passive:false});}function onPickTap(e){const btn=e.target&&e.target.closest&&e.target.closest("[data-practice]");if(!btn)return;if(e.type==="touchend"||e.type==="pointerup")e.preventDefault();const now=Date.now();if(now<lockUntil)return;lockUntil=now+600;practice(btn.dataset.practice,btn.dataset.size);}const pick=$("pick");if(pick){pick.addEventListener("click",onPickTap);pick.addEventListener("pointerup",e=>{if(e.pointerType!=="mouse")onPickTap(e);},{passive:false});pick.addEventListener("touchend",onPickTap,{passive:false});}const bins=$("bins");if(bins){let lock=0;function hit(e){const btn=e.target.closest&&e.target.closest(".bin");if(!btn||state.specOpen)return;const now=Date.now();if(now<lock)return;lock=now+280;tapBin(btn);}bins.addEventListener("click",hit);bins.addEventListener("pointerup",e=>{if(e.pointerType!=="mouse")hit(e);});bins.addEventListener("touchend",e=>{e.preventDefault();hit(e);},{passive:false});}})();
